server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



fdfs:
  so-timeout: 1501
  connect-timeout: 800
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
   # - 101.200.56.190:22122
    - 119.45.207.191:22122

mingrui:
  upload:
    path:
      windows: T:\\images
      linux: /sss/images
    img:
      host: http:\\image.baidushop.com
      # host: http://101.200.56.190/
