server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



mingrui:
  upload:
    path:
      windows: T:\\images
      linux: /sss/images
    img:
      host: http:\\image.baidushop.com