logging:
  level:
    com.baidu: info


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baidu-shop?useSSL=true&nullNamePatternMatchesAll=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    # 数据库连接用户
    username: root
    # 数据库连接密码
    password: root
    # 驱动名称
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 101.200.56.190
    database: 0
    password: redis222


server:
  port: 5555
