spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 是否确认回调
    publisher-confirm-type: correlated
    # 是否返回回调
    publisher-returns: true
    virtual-host: /
    # 手动确认
    listener:
      simple:
        acknowledge-mode: manual
  application:
    name: template-server
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8004

mrshop:
  static:
    html:
      path: T:\static-html\item #生成的html文件存储的路径

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true