spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baidu-shop?useSSL=true&nullNamePatternMatchesAll=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  application:
    name: addr-server
#开启驼峰命名法
mybatis:
  configuration:
    map-underscore-to-camel-case: true


# jwt 配置
mrshop:
  jwt:
    pubKeyPath: T:\severe\rea.pub # 公钥地址
    cookieName: MRSHOP_TOKEN # cookie的名称
server:
  port: 8991